-- ======================================================
-- PROYECTO: LIGA DE FÚTBOL
-- SCRIPT: RELACIONES Y RESTRICCIONES ADICIONALES
-- ======================================================

USE soccerdb;

-- =============================
-- RELACIONES CON ELIMINACIÓN EN CASCADA
-- =============================

ALTER TABLE EQUIPO_TELEFONO
  DROP FOREIGN KEY EQUIPO_TELEFONO_ibfk_1,
  ADD CONSTRAINT FK_EQUIPO_TELEFONO_EQUIPO
  FOREIGN KEY (id_equipo) REFERENCES EQUIPO(id_equipo)
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EQUIPO_ENTRENADOR
  DROP FOREIGN KEY EQUIPO_ENTRENADOR_ibfk_1,
  DROP FOREIGN KEY EQUIPO_ENTRENADOR_ibfk_2,
  ADD CONSTRAINT FK_EQUIPO_ENTRENADOR_EQUIPO
  FOREIGN KEY (id_equipo) REFERENCES EQUIPO(id_equipo)
  ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT FK_EQUIPO_ENTRENADOR_ENTRENADOR
  FOREIGN KEY (id_entrenador) REFERENCES ENTRENADOR(id_entrenador)
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CONTRATO
  DROP FOREIGN KEY CONTRATO_ibfk_1,
  DROP FOREIGN KEY CONTRATO_ibfk_2,
  ADD CONSTRAINT FK_CONTRATO_JUGADOR
  FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador)
  ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT FK_CONTRATO_EQUIPO
  FOREIGN KEY (id_equipo) REFERENCES EQUIPO(id_equipo)
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ESTADISTICA
  DROP FOREIGN KEY ESTADISTICA_ibfk_1,
  DROP FOREIGN KEY ESTADISTICA_ibfk_2,
  ADD CONSTRAINT FK_ESTADISTICA_PARTIDO
  FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido)
  ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT FK_ESTADISTICA_JUGADOR
  FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador)
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TRANSFERENCIA
  DROP FOREIGN KEY TRANSFERENCIA_ibfk_1,
  ADD CONSTRAINT FK_TRANSFERENCIA_JUGADOR
  FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador)
  ON DELETE CASCADE ON UPDATE CASCADE;

-- =============================
-- CHECKS Y VALIDACIONES LÓGICAS
-- =============================

ALTER TABLE PARTIDO
  ADD CONSTRAINT CHK_Goles_Positivos CHECK (goles_local >= 0 AND goles_visitante >= 0);

ALTER TABLE TABLA_POSICIONES
  ADD CONSTRAINT CHK_Partidos_No_Negativos
  CHECK (partidos_jugados >= 0 AND ganados >= 0 AND empatados >= 0 AND perdidos >= 0);

ALTER TABLE TRANSFERENCIA
  ADD CONSTRAINT CHK_VALOR_POSITIVO
  CHECK (valor_transferencia >= 0);

-- =============================
-- CAMPOS ÚNICOS
-- =============================

ALTER TABLE EQUIPO ADD CONSTRAINT UQ_Nombre_Equipo UNIQUE (nombre);
ALTER TABLE ENTRENADOR ADD CONSTRAINT UQ_Nombre_Entrenador UNIQUE (nombre, apellido);
ALTER TABLE ESTADIO ADD CONSTRAINT UQ_Nombre_Estadio UNIQUE (nombre);
ALTER TABLE JUGADOR ADD CONSTRAINT UQ_Dorsal_Equipo UNIQUE (dorsal, nombre, apellido);
